version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - "9200:9200"
    restart: "always"
    container_name: es
  kibana:
    image: kibana:6.8.5
    ports:
      - "5601:5601"
    restart: "always"
    container_name: kibana
    volumes:
      - ./kibana.yml:/etc/kibana/kibana.yml
    links:
      - elasticsearch:es