version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pro
    expose:
      - 3306
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf